"""init schema (assets + simulated_trades)

Revision ID: 0a0856b12af6
Revises:
Create Date: 2026-06-02 07:19:15.462333

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a0856b12af6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("quote_currency", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_symbol"), "assets", ["symbol"], unique=True)
    op.create_table(
        "simulated_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "open", "closed", "cancelled", name="trade_status"),
            nullable=False,
        ),
        sa.Column("amount_invested", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("fee_model", sa.String(length=30), nullable=False),
        sa.Column("fee_currency", sa.String(length=10), nullable=False),
        sa.Column("entry_fee_rate", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("entry_fee_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("exit_fee_rate", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("exit_fee_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("exit_gross_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("exit_net_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("pnl_net", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("pnl_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulated_trades_asset_id"), "simulated_trades", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_simulated_trades_status"), "simulated_trades", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulated_trades_status"), table_name="simulated_trades")
    op.drop_index(op.f("ix_simulated_trades_asset_id"), table_name="simulated_trades")
    op.drop_table("simulated_trades")
    op.drop_index(op.f("ix_assets_symbol"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
