"""add binance metadata on assets

Revision ID: 650f8967bf5c
Revises: e38ca986140e
Create Date: 2026-06-02 08:25:23.520487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650f8967bf5c'
down_revision: Union[str, None] = 'e38ca986140e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('binance_symbol', sa.String(length=30), nullable=True))
    op.add_column('assets', sa.Column('binance_status', sa.String(length=20), nullable=True))
    op.add_column('assets', sa.Column('market_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'market_synced_at')
    op.drop_column('assets', 'binance_status')
    op.drop_column('assets', 'binance_symbol')
    # ### end Alembic commands ###
