"""add short_trades table

Revision ID: 8586720d9de6
Revises: 89197adee783
Create Date: 2026-06-03 14:09:03.768517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8586720d9de6'
down_revision: Union[str, None] = '89197adee783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('amount_invested', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('spread_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('slippage_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('funding_rate_daily', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('entry_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('exit_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('funding_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('pnl_gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pnl_net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('params_key', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_trades_asset_id'), 'short_trades', ['asset_id'], unique=False)
    op.create_index(op.f('ix_short_trades_run_id'), 'short_trades', ['run_id'], unique=False)
    op.create_index(op.f('ix_short_trades_status'), 'short_trades', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_trades_status'), table_name='short_trades')
    op.drop_index(op.f('ix_short_trades_run_id'), table_name='short_trades')
    op.drop_index(op.f('ix_short_trades_asset_id'), table_name='short_trades')
    op.drop_table('short_trades')
    # ### end Alembic commands ###
