"""add stop_price take_profit_price on simulated_trades

Revision ID: 89197adee783
Revises: dd98ea36266e
Create Date: 2026-06-02 16:08:54.162893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89197adee783'
down_revision: Union[str, None] = 'dd98ea36266e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulated_trades', sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('simulated_trades', sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulated_trades', 'take_profit_price')
    op.drop_column('simulated_trades', 'stop_price')
    # ### end Alembic commands ###
