"""add strategy_decisions

Revision ID: dd98ea36266e
Revises: 650f8967bf5c
Create Date: 2026-06-02 13:58:23.146656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd98ea36266e'
down_revision: Union[str, None] = '650f8967bf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_decisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('candle_close_time', sa.BigInteger(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ema_fast', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_slow', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_trend', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('atr', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('position_state', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('params_key', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('simulated_trade_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['simulated_trade_id'], ['simulated_trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timeframe', 'candle_close_time', 'params_key', name='uq_strategy_decision_candle')
    )
    op.create_index('ix_strategy_decisions_action', 'strategy_decisions', ['action'], unique=False)
    op.create_index('ix_strategy_decisions_asset_id', 'strategy_decisions', ['asset_id'], unique=False)
    op.create_index('ix_strategy_decisions_candle_close_time', 'strategy_decisions', ['candle_close_time'], unique=False)
    op.create_index('ix_strategy_decisions_run_id', 'strategy_decisions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategy_decisions_run_id', table_name='strategy_decisions')
    op.drop_index('ix_strategy_decisions_candle_close_time', table_name='strategy_decisions')
    op.drop_index('ix_strategy_decisions_asset_id', table_name='strategy_decisions')
    op.drop_index('ix_strategy_decisions_action', table_name='strategy_decisions')
    op.drop_table('strategy_decisions')
    # ### end Alembic commands ###
