"""add indexes opened_at closed_at asset_status

Revision ID: e38ca986140e
Revises: 386e4fcbffb5
Create Date: 2026-06-02 08:04:34.473108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38ca986140e'
down_revision: Union[str, None] = '386e4fcbffb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_simulated_trades_asset_status', 'simulated_trades', ['asset_id', 'status'], unique=False)
    op.create_index(op.f('ix_simulated_trades_closed_at'), 'simulated_trades', ['closed_at'], unique=False)
    op.create_index(op.f('ix_simulated_trades_opened_at'), 'simulated_trades', ['opened_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulated_trades_opened_at'), table_name='simulated_trades')
    op.drop_index(op.f('ix_simulated_trades_closed_at'), table_name='simulated_trades')
    op.drop_index('ix_simulated_trades_asset_status', table_name='simulated_trades')
    # ### end Alembic commands ###
