"""Univers meanrev-v2 : top-100 paires USDT liquides (snapshot 2026-06-10, gen_universe_v2.py)."""
PAIRS = (
    "BTCUSDT", "ETHUSDT", "ZECUSDT", "SOLUSDT", "XRPUSDT", "WLDUSDT", "XLMUSDT", 
    "NEARUSDT", "BNBUSDT", "DOGEUSDT", "BABYUSDT", "TRXUSDT", "ADAUSDT", "ALLOUSDT", 
    "SUIUSDT", "ENAUSDT", "HOMEUSDT", "PEPEUSDT", "TONUSDT", "TAOUSDT", "STGUSDT", 
    "SAHARAUSDT", "CHZUSDT", "KATUSDT", "LINKUSDT", "STRAXUSDT", "LTCUSDT", "AVAXUSDT", 
    "SENTUSDT", "UUSDT", "ONDOUSDT", "BCHUSDT", "INJUSDT", "HAEDALUSDT", "WLFIUSDT", 
    "UTKUSDT", "FETUSDT", "CHIPUSDT", "OPNUSDT", "PENGUUSDT", "ASTERUSDT", "AAVEUSDT", 
    "HOLOUSDT", "TRUMPUSDT", "MOVEUSDT", "HMSTRUSDT", "IOUSDT", "FILUSDT", "HBARUSDT", 
    "UNIUSDT", "DASHUSDT", "PUMPUSDT", "IDUSDT", "SPKUSDT", "ARBUSDT", "RENDERUSDT", 
    "DEXEUSDT", "JSTUSDT", "DOTUSDT", "BIOUSDT", "EPICUSDT", "JTOUSDT", "ICPUSDT", 
    "MORPHOUSDT", "APTUSDT", "ZBTUSDT", "ALTUSDT", "FFUSDT", "LUNCUSDT", "ZROUSDT", 
    "XPLUSDT", "ATOMUSDT", "VIRTUALUSDT", "CRVUSDT", "MANTRAUSDT", "ZKUSDT", "HIVEUSDT", 
    "OSMOUSDT", "TIAUSDT", "WALUSDT", "PORTALUSDT", "FORMUSDT", "AVNTUSDT", "HEIUSDT", 
    "MEGAUSDT", "POLUSDT", "SUSDT", "RUNEUSDT", "LRCUSDT", "SHIBUSDT", "ARUSDT", "OPUSDT", 
    "ZAMAUSDT", "OPENUSDT", "ORDIUSDT", "PARTIUSDT", "SEIUSDT", "NEIROUSDT", "CAKEUSDT", 
    "PENDLEUSDT", 
)
